### ISSUE TITLE
Guestbook/Kubeless/Python

### ISSUE THREAD

**Issue by vallard** [fonk-apps/fonk-examples#17]

**Comment by petecj2** [comment]
Be sure to check out:

https://github.com/fonk-apps/fonk-examples/issues/14

**Comment by vallard** [comment]
blocked on https://github.com/kubeless/kubeless/issues/934.  Hoping I get time to do a PR for the kubeless to update the runtime container to allow for cors.

**Comment by petecj2** [comment]
Confirmed the PR closes this
