### ISSUE TITLE
New function to delete complete database - Fission/Python

### ISSUE THREAD

**Issue by juliogomez** [fonk-apps/fonk-examples#7]
Let's have a new function that deletes the complete database. 

After spending some time with the different FaaS engines you might find out compatibility issues when writing to the DB. When you update the DB with one engine, then the next one cannot read it because they are slightly incompatible formats. 

During a demo, when you want to change from one FaaS engine to the next one, you need to easily delete the whole DB and work with an empty one. It also helps when your list of DB entries is so long that you need to scroll down during the demo.

**Comment by juliogomez** [comment]
#8 is the PR to implement this new function.

**Comment by petecj2** [comment]
I have mixed feelings about this one, but I'm not 100% sure either way. Strictly speaking, Guestbook doesn't support Delete and you can purge/restart the Mongo DB using kubectl commands. But I get the convenience of this so I'm going to merge it and see if, as the community grows, people have a strong feeling about this or are willing to wait for Delete, Update, and Read as part of the future planned ToDos app.
